language: python
sudo: required
dist: xenial
python:
  - "3.7"
cache:
  - pip
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 -o ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - tox
after_success:
  - coverage erase
  - coverage combine
  - "coverage xml"
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT -t coverage.py
before_deploy:
  - "sed -i -e \"s/\\[VERSION\\]/${TRAVIS_TAG}/\" setup.py"

provider: pypi
  skip_cleanup: true
  distributions: sdist
  on:
    tags: true
  user:
    secure: >-
      HyNtmrgPlnm6YueU9pM1n1AX5NUjsETMqdM8GgBXo8h42UCiUkJ+DvwMzKrdD9AM2oJwPbB4c
      xTXvdmbahlEiTz4YZifmCDjP2P8OuQi9Pc1RPIz37PP21yidimYy36LF7puSA+9oGjmQP3+0Z
      +IsEt27zXP/tUM1tlig5ZsgFW/52eA9P7f98b3J4dJRzFxgSe6QU9Z9N7bRYk+YAmsDao1yz3
      I/ULpofD4JQw81fbowvzb3ws2hsZ5WnzOgq+aAfSmET9c1UxalwlW3hBR+Kn+YeFF8YHMTYJ3
      stK3oDDLIUACenWnfxP4kks0JRDZhBkJQuO3Lxs95sLuVYW3cM8AUBKjRPUsIoZQszgCs7sEr
      4WMyXsrICsCPZ/w4gaNShQs4oEta7SKyicbwTuMqfipaO8v3iuHMH2TiXU1lE1MGROcEIGxnE
      yEBqd9sH2sDoF4dzeZGIXTLhOsdBS+hrmfbbefgcnmGCvp3uSSKYvTckgmKHKzi5fREJ4QAVt
      rpTZJfa+tr/kI3fxZlFvlvhaDGGW3LPf1tHEC6ynMVZ/dhy97KYeSJdI3/V5JAREk7zWhK64v
      MX/cmXHZzQwTLYlu/4POkIQpI4R/80rQxZHgYtPhn+uM0VUcEnfJEmYo1jkfaUz1E8lRreLDO
      tecmvOY6txtit8uO+QYLLkYLNg=
  password:
    secure: >-
      xACNGCe2ZYI0bp7Kt8ofL9X3mdsjoYd0qxbhcP0qe/6/Sije11yiS1W0uZ9Vg8y6YcHDCxDjd
      mrH+OXfvO/2PTv/Fd7n/dlql2qV4nMGBvg70xukDjPV7kI3bHmNJfqXLj3fGY6ITAeMbBvwsz
      mAR3j0SPmou3GaAFRkguvnLXWAmurg8AwU+MvqLbedqrvFR8FRR5F3oa+Pr8dK2zeiZ/UWp9E
      J6D0Nd5lGOvu6kkCFHsrZ2aLb+ExzDtmM5cBjSS9h3KHRdsfOF3wNdFf/6KpawG/EeNDpwhjE
      BLLrR3qV3j6Mq/Lgv0gUJCsAF32SM6vDwIfz4AKU4oc8/6oxgjg+bWAPqbyMzyHEvcUgjn+9E
      gP9I9y3Fu7+9VQIAlTWfV+lJ6iHv2ti46Ivcp5UaWKfZRRq+Bjj3tYqWnDTl9j1McWYGK7h1U
      8uTvTE39L4m6ArFHpzrkxr5eHLOsCep2oLDA9MeXmjFmCjnIb4x6itKmEkZqizIi8vDm6NQ7S
      DKVW6NTis/yQWLvbQSt9xmo+HysP5OheHIrkrgrStpTTzamOq4q4N4xEvqAsMRbUp5kwnH6RX
      NJxoTvPMENMqqzL5In2TvCmVtojLXDRzRGDA56nr2NbSBN8d4xmRFD+P7lcOM+8JKLlu2NxQG
      4fTD5gWBXYRCW0sOgpyBM2s0Fg=
