name: Deploy

on:
  push:
    tags:
      - "*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: deploy

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "^3.0"
          architecture: "x64"
      - name: Install dependencies
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry install
      - name: Writing the version
        run: poetry version ${{ github.ref_name }}
      - name: Create the package
        run: poetry build -f sdist
      - name: Deploy
        run: poetry publish -u __token__ -p ${{ secrets.PYPI_TOKEN }}
