# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: python:alpine

    steps:
    - uses: actions/checkout@v2
    - name: Install curl
      run: apk update && apk add -q curl
    - name: Download coverage
      run: |
        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 \
          -o ./cc-test-reporter
        chmod +x ./cc-test-reporter
        ./cc-test-reporter before-build
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test & Send Coverage
      run: |
        tox -p all -q
        export TEST_RESULT=${?}
        coverage xml
        ./cc-test-reporter after-build --exit-code $TEST_RESULT -t coverage.py
