# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: python:alpine

    steps:
    - uses: actions/checkout@v2
    - name: Install curl
      run: apk update && apk add -q curl git
    - name: Download coverage
      run: |
        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 \
          -o ./cc-test-reporter
        chmod +x ./cc-test-reporter
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test & Send Coverage
      run: |
        export GIT_COMMITTED_AT=$(date +%s)
        ./cc-test-reporter before-build
        tox -p all -q
        export TEST_RESULT=${?}
        export GIT_BRANCH=$(basename ${{ github.repository }} ${{ github.repository_owner }})
        echo $GIT_BRANCH
        coverage xml
        ./cc-test-reporter after-build --exit-code $TEST_RESULT -t coverage.py
      env:
        GIT_COMMIT_SHA: ${{ github.sha }}
        CI_BUILD_ID: ${{ github.run_number }}
        CI_BUILD_URL: https://github.com/hiroaki-yamamoto/WTF-OTP/runs/${{ github.run_number }}
